version: '3.8'

services:
  sqlserver:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
    ports:
      - "1433:1433"

  product-api:
    build:
      context: ./ProductAPI
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  cart-api:
    build:
      context: ./CartAPI
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  order-api:
    build:
      context: ./OrderAPI
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
